NotBlocket2/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace NotBlocket2.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<IdentityUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

NotBlocket2/Controllers/NotBlocketController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using NotBlocket2.Models;
using Umbraco.Core.Models;

namespace NotBlocket2.Controllers {
    public class NotBlocketController : Controller {

        [HttpGet]
        public IActionResult Start() {

            List<string> locationNames = new List<string>();
            List<int> ProfileCountPerLocation = new List<int>();
            string errormsg = string.Empty;

            Graphmethods gm = new Graphmethods();

            gm.GetLocationsWithDataSet(out locationNames, out ProfileCountPerLocation, out errormsg);

            ViewBag.LocationNames = locationNames;
            ViewBag.ProfileCountPerLocation = ProfileCountPerLocation;
            return View();
        }

        [HttpGet]
        public IActionResult SearchResults(string search, string sort) {

            //Dealing with the null-values
            if (sort == null) { sort = "Name"; }
            if (search != null) {

                ViewBag.search = search;
                ViewBag.sort = sort;

                //Get the Ad list
                List<Ad> Adlist = new List<Ad>();
                AdMethods pm = new AdMethods();
                string error = "";
                Adlist = pm.GetAdsWithDataSet2(sort, search, out error);
                ViewBag.error = error;
                return View(Adlist);
            }
            return RedirectToAction("Start");
        }



        // Functions related to creating profiles
        [HttpGet]
        public IActionResult CreateAccount() {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAccount(Profile p) {
            ProfileMethods pm = new ProfileMethods();
            int i = 0;
            string error = "";

            if (!ModelState.IsValid) {
                ViewBag.error = "error: " + error;
                ViewBag.antal = i;
                return View(p);
            }

            i = pm.InsertProfile(p, out error);
            ViewBag.error = error;
            ViewBag.antal = i;
            return RedirectToAction("ProfilesView");

        }

        [HttpGet]
        public IActionResult CreateAd() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAd(Ad ad, IFormFile file) {
            AdMethods am = new AdMethods();
            int i = 0;
            string error = "";

            if (!ModelState.IsValid) {
                ViewBag.error = "error: " + error;
                ViewBag.antal = i;
                return View();
            }

            ad.ImagePath = await AdMethods.SaveFileAsync(file);

            am.InsertAd(ad, out error);
            ViewBag.error = error;
            ViewBag.antal = i;
            return RedirectToAction("AdsView");

        }


        [HttpGet]
        public IActionResult Deleteprofile(int id) {
            // Remove the row with the specified ID from the database
            ProfileMethods pm = new ProfileMethods();
            string error = "";
            pm.DeleteProfile(id, out error);
            ViewBag.error = error;

            return RedirectToAction("ProfilesView");
        }

        [HttpGet]
        public IActionResult DeleteAd(int id) {
            // Remove the row with the specified ID from the database
            AdMethods am = new AdMethods();
            string error = "";
            am.DeleteAd(id, out error);
            ViewBag.error = error;

            return RedirectToAction("AdsView");
        }

        [HttpGet]
        public IActionResult Editprofile(int id) {
            //Profile p = new Profile();
            string error = "";
            ProfileMethods pm = new ProfileMethods();
            Profile p = pm.GetProfileById(id, out error);
            return View(p);
        }

        [HttpPost]
        public ActionResult Editprofile(Profile pd) {
            if (ModelState.IsValid) {
                // updt databse and go back to list
                ProfileMethods pm = new ProfileMethods();
                string error = "";

                pm.UpdateProfile(pd, out error);
                ViewBag.error = error;
                return RedirectToAction("ProfilesView");
                //return View(pd);
            }
            return View(pd);
            //return RedirectToAction("Editprofile");
        }

        [HttpGet]
        public IActionResult EditAd(int Id) {
            string error = "";

            AdMethods pm = new AdMethods();
            Ad ad = pm.GetAdById(Id, out error);
            ViewBag.error = error;
            if (ad != null) {
                return View(ad);
            }
            else {
                return View(ad);
            }
        }

        /*
        [HttpPost]
        public async Task<IActionResult> EditAdWithFile(Ad ad, IFormFile file) {
            AdMethods am = new AdMethods();
            string error = "";
            string errorMessage = "";

            
            if (ModelState.IsValid) {
                try {
                    // Save the file
                    //AdMethods am = new AdMethods();
                    string imagePath = await AdMethods.SaveFileAsync(file);

                    // Update the ad with the file information
                    ad.ImagePath = imagePath;
                }
                catch (Exception ex) {
                    errorMessage = ex.Message;
                }
            }
            am.UpdateAd(ad, out error);
            ViewBag.error = errorMessage + error;
            //return View(ad);
            return RedirectToAction("AdsView");
            //return RedirectToAction("EditAd");
        }
        */

        [HttpPost]
        public IActionResult EditAd(Ad ad) {
            string error = "";
            if (ModelState.IsValid) {
                // updt databse and go back to list
                AdMethods pm = new AdMethods();
                

                pm.UpdateAd(ad, out error);
                ViewBag.error = error;
                return RedirectToAction("AdsView");
                //return View(ad);
            }

            var errorMessage = "Validation errors: ";
            foreach (var errorr in ModelState.Values) {
                if (errorr.Errors.Count > 0) {
                    errorMessage += errorr.Errors[0].ErrorMessage + "; ";
                }
            }
            ViewBag.error = error + errorMessage;
            return View(ad);
        }



        [HttpGet]
        public ActionResult ProfilesView() {
            List<Profile> Profilelist = new List<Profile>();
            ProfileMethods pm = new ProfileMethods();
            string error = "";
            Profilelist = pm.GetPersonWithDataSet(out error);
            ViewBag.error = error;
            return View(Profilelist);
        }

        /*
        //Display login view
        public IActionResult Login() {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Profile std) {
            if (ModelState.IsValid) { //checking model state

                //update student to db
                ViewBag.error = "works";
                return RedirectToAction("Start");
            }
            ViewBag.error = "someError";
            return View(std);
            
        }
        
        [HttpGet]
        public IActionResult LoginPage() {
            return View();
        }
        */
		
		public IActionResult AdsView() {
            ProfileMethods pm = new ProfileMethods();
            LocationMethods lm = new LocationMethods();
            AdMethods am = new AdMethods();


			string selectedValue = null;
		    if (Request.Method == "POST") {
				selectedValue = Request.Form["Category"];
			}
			ViewBag.location = selectedValue;
            
			ViewModelProfileAdsLocation myModel = new ViewModelProfileAdsLocation
            {
                ProfileList = pm.GetPersonWithDataSet(out string errormsg),
                LocationList = lm.GetLocationsWithDataSet(out string errormsg2),

                //ad list for the categories dropdown
                AdList = am.GetAdsWithDataSet(out string errormsg3),

                //seperate ad list for the view
				FilterdAdList = am.GetAdsWithDataSet(out string errormsg4, selectedValue)

			};
            ViewBag.error = "1: " + errormsg + "2: " + errormsg2 + "3: " + errormsg3 + "4: " + errormsg4;


			return View(myModel);
        }
    
    }
}

NotBlocket2/Views/NotBlocket/AdsView.cshtml
@model NotBlocket2.Models.ViewModelProfileAdsLocation

<h1>Ads</h1>
@*
@ViewBag.error
@ViewBag.errorx
*@

<div class="row">
	<div class="form-group col-md-4">
		<form asp-action="AdsView" method="post">
			<div class="form-group">
				<select class="form-control" id="Category" name="Category">
					@foreach (var category in Model.AdList.Select(x => x.Category).Distinct()) {
						<option value="@category">@category</option>
					}
				</select>
			</div>
			<div class="form-group">
				<input type="submit" value="Apply Filter" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>


<table class="table">
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Description</th>
		<th>Category</th>
		<th>Image</th>
		<th></th>

	</tr>
	@foreach (NotBlocket2.Models.Ad Ad in Model.FilterdAdList) {
		<tr>
			<td>@Ad.Name</td>
			<td>@Ad.Price</td>
			<td>@Ad.Description</td>
			<td>@Ad.Category</td>
			<td><img src="@Ad.ImagePath" alt="No Image" style="max-width:250px; max-height:150px;"></td>
		    <td>
				<button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("EditAd", "NotBlocket", new { id = Ad.Id })'">Edit</button>
          
               <button type="button" class="btn btn-danger" onclick="if (confirm('Are you sure you want to delete this Ad?')) { location.href='@Url.Action("DeleteAd", "NotBlocket", new { id = Ad.Id })' }">Delete</button>

            </td>
		</tr>
	}

</table>

NotBlocket2/Views/NotBlocket/CreateAccount.cshtml
@model NotBlocket2.Models.Profile

@{
    ViewData["Title"] = "Creat New Account";
}
@ViewBag.error
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Creat New Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

NotBlocket2/Views/NotBlocket/CreateAd.cshtml
@model NotBlocket2.Models.Ad

@{
    ViewData["Title"] = "CreateAd";
}
<h3>Create Ad</h3>


<form asp-controller="NotBlocket" asp-action="CreateAd" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="File">Choose Image:</label>
        <input type="file" id="model.File" name="File" required />
    </div>
    <div class="form-group">
        <label for="Name">Name:</label>
        <input type="text" id="model.Name" asp-for=Name required />
    </div>
    <div class="form-group">
        <label for="Description">Description:</label>
        <input type="text" id="model.Description" asp-for=Description />
    </div>
    <div class="form-group">
        <label for="Category">Category:</label>
        <input type="text" id="model.Category" asp-for=Category />
    </div>
    <div class="form-group">
        <label for="Price">Price:</label>
        <input type="number" id="model.Price" asp-for=Price required />
    </div>
    <div class="form-group">
        <button type="submit">Upload Ad with Image</button>
    </div>
</form>

NotBlocket2/Views/NotBlocket/EditAd.cshtml
@model NotBlocket2.Models.Ad

@{
    ViewData["Title"] = "Edit Ad";
}

Edit Ad
@ViewBag.error

<form method="post" action="@Url.Action("EditAd", "NotBlocket")">
    @Html.AntiForgeryToken()

    @*
    <div class="form-group">
        <label for="File">Choose New Image:</label>
        <input type="file" id="File" name="File" />
    </div>
    *@
    <div class="form-group"> 
        <label for="Name">Name:</label>
        <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
         @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Description">Description:</label>
        <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">

    </div>
    <div class="form-group">
        <label for="Category">Category:</label>
        <input type="text" class="form-control" id="Category" name="Category" value="@Model.Category">

    </div>
    <div class="form-group">
        <label for="Price">Price:</label>
        <input type="number" class="form-control" id="Price" name="Price" value="@Model.Price">
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Profile_Id">Profile_Id:</label>
        <input type="number" class="form-control" id="Profile_Id" name="Profile_Id" value="@Model.Profile_Id">

    </div>
    <div class="form-group">
        <label for="ImagePath">ImagePath:</label>
        <input type="text" class="form-control" id="ImagePath" name="ImagePath" value="@Model.ImagePath">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

NotBlocket2/Views/NotBlocket/Editprofile.cshtml
@model NotBlocket2.Models.Profile
@ViewBag.error


<form method="post" action="@Url.Action("Editprofile", "NotBlocket")">
    @Html.AntiForgeryToken()

    <div class="form-group"> 
        <label for="Name">Name:</label>
        <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
         @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Email">Email:</label>
        <input type="email" class="form-control" id="Email" name="Email" value="@Model.Email">
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Password">Password:</label>
        <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">
        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Location_Id">Location_Id:</label>
        <input type="number" class="form-control" id="Location_Id" name="Location_Id" value="@Model.Location_Id">
        @Html.ValidationMessageFor(model => model.Location_Id, "", new { @class = "text-danger" })
    </div>
    <input type="hidden" name="Id" value="@Model.Id">
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

NotBlocket2/Views/NotBlocket/Editprofile2.cshtml
@model NotBlocket2.Models.Profile

@{
    ViewData["Title"] = "Editprofile2";
}

<h1>Editprofile2</h1>

<div>
    <h4>Profile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

NotBlocket2/Views/NotBlocket/Login.cshtml
@model NotBlocket2.Models.Profile

@{
    ViewData["Title"] = "Login page";
}
<h1>Login</h1>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@*
<form action="SearchResults" method="post">
    <div class="form-group">
        <input type="text" class="form-control" name="Email" placeholder="Email">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="Password" placeholder="Password">
    </div>
    <input type="submit" value="Login" class="btn btn-primary" />
</form>

*@


@ViewBag.error

<div>
    <a asp-action="CreatAccount">Create New Account</a>
</div>

<div>
    <a asp-action="Start">Start</a>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<canvas id="myChart"></canvas>

NotBlocket2/Views/NotBlocket/ProfilesView.cshtml
@model IEnumerable<NotBlocket2.Models.Profile>

@{
    ViewData["Title"] = "Profiles";
}

<h1>Profiles</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location_Id)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location_Id)
                </td>

                <td>
                  <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Editprofile", "NotBlocket", new { id = item.Id })'">Edit</button>
          
                  <button type="button" class="btn btn-danger" onclick="if (confirm('Are you sure you want to delete this profile?')) { location.href='@Url.Action("Deleteprofile", "NotBlocket", new { id = item.Id })' }">Delete</button>

                </td>
            </tr>
        }
    </tbody>

</table>


<p>    eventuellt felmeddelande:  @ViewBag.error </p>

NotBlocket2/Views/NotBlocket/SearchResults.cshtml
@model IEnumerable<NotBlocket2.Models.Ad>

@{
	ViewData["Title"] = "SearchResults";
}
<h1>Searchresult</h1>

Search term: @ViewBag.search

sort: @ViewBag.sort

@ViewBag.error

<table class="table">
    <thead>
        <tr>
            <th>
                <a href="SearchResults?search=@ViewBag.search&sort=Id">
                @Html.DisplayNameFor(model => model.Id)
                </a>
            </th>
            <th>
                <a href="SearchResults?search=@ViewBag.search&sort=Name">
                @Html.DisplayNameFor(model => model.Name)
                </a>
            </th>
            <th>
                @*Enables sorting by price while keeping the searchterm*@

                <a href="SearchResults?search=@ViewBag.search&sort=Price">
                    @Html.DisplayNameFor(model => model.Price)
                </a>
            </th>

        </tr>
    </thead>
    
    
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>
        }
    </tbody>
    
</table>

NotBlocket2/Views/NotBlocket/SelectWithDataReader.cshtml
@model IEnumerable<NotBlocket2.Models.Profile>

@{
    ViewData["Title"] = "SelectWithDataReader";
}

<h1>SelectWithDataReader</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
            </tr>
        }
    </tbody>
</table>