Lab1/5TF048_lab1/Models/Dinner.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.Build.Framework;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace _5TF048_lab1.Models
{
    public class Dinner
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public int NumberofPortions { get; set; }
        public string Review { get; set; }

        [Display(Name = "dl Flour")]
        public int Flour { get; set; }

        [Display(Name = "nr of Eggs")]
        public int Egg { get; set; }

        [Display(Name = "Salt (spoons)")]
        public int Salt { get; set; }

        [Display(Name = "Milk (dl)")]
        public int Milk { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public Dinner() { 
            Flour=0; 
            Egg=0;
            Salt=0;
            Milk=0;
            Name= string.Empty;

        }

        public void Calculate()
        {
            Flour = Flour* NumberofPortions;
            Egg = Egg*2* NumberofPortions;
            Salt = Salt*5*NumberofPortions;
            Milk = Milk * 31 * NumberofPortions;
        }
    }

}

Lab1/5TF048_lab1/Models/ErrorViewModel.cs
namespace _5TF048_lab1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab1/5TF048_lab1/Controllers/FoodController.cs
using System;
using System.Diagnostics;
using _5TF048_lab1.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Newtonsoft.Json;

namespace _5TF048_lab1.Controllers
{
    public class FoodController : Controller
    {
        [HttpGet]
        public IActionResult Start(){
            return View();
        }

        [HttpPost]
        public IActionResult Recept(IFormCollection col) {

            Dinner D = new Dinner();
            D.Name = col["Name"];
            D.NumberofPortions = Convert.ToInt32(col["NumberofPortions"]);
            D.Date = Convert.ToDateTime(col["date"]);
            D.Calculate();

            string s = JsonConvert.SerializeObject(D);
            HttpContext.Session.SetString("Foodsession", s);

            return View(D);
        }

        [HttpGet]
        public IActionResult Evaluate() {
            List<SelectListItem> list = new List<SelectListItem>();

            list.Add(new SelectListItem { Text = "uruselt", Value = "0" });
            list.Add(new SelectListItem { Text = "Dåligt", Value = "1" });
            list.Add(new SelectListItem { Text = "INTE BRA", Value = "2" });
            list.Add(new SelectListItem { Text = "ok", Value = "3" });
            list.Add(new SelectListItem { Text = "inte dåligt", Value = "4" });
            list.Add(new SelectListItem { Text = "bra", Value = "5" });

            return View(list);
        }

        [HttpPost]
        public ActionResult Finish(IFormCollection col) {
            Dinner m = new Dinner();
            string s = HttpContext.Session.GetString("Foodsession");
            m = JsonConvert.DeserializeObject<Dinner>(s);
            int review = Convert.ToInt32(col["Review"]);

            List<SelectListItem> list = new List<SelectListItem>();

            list.Add(new SelectListItem { Text = "uruselt", Value = "0" });
            list.Add(new SelectListItem { Text = "Dåligt", Value = "1" });
            list.Add(new SelectListItem { Text = "INTE BRA", Value = "2" });
            list.Add(new SelectListItem { Text = "ok", Value = "3" });
            list.Add(new SelectListItem { Text = "inte dåligt", Value = "4" });
            list.Add(new SelectListItem { Text = "bra", Value = "5" });

            m.Review = list[review].Text;

            s = JsonConvert.SerializeObject(m);
            HttpContext.Session.SetString("Foodsession", s);

            return View(m);
        }

    }
}

Lab1/5TF048_lab1/Controllers/HomeController.cs
using System.Diagnostics;
using _5TF048_lab1.Models;
using Microsoft.AspNetCore.Mvc;

namespace _5TF048_lab1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Food() {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab1/5TF048_lab1/Views/Food/Evaluate.cshtml
@model List<SelectListItem>

@{
    ViewData["Title"] = "Evaluate";
}

<h2>Evaluate</h2>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Finish" method="post">
            <div class="form-group">
                @foreach (SelectListItem item in Model){
                <input type ="radio" name="Evaluate" value="@Html.DisplayFor(model => item.Value)">@item.Text<br />

                }
            </div>
            <div class="form-group">
                <input type="submit" value="Finish" class="btn btn-default" />
            </div>
        </form>


    </div>
</div>


<div>
    <a asp-action="Start">Back to Start</a>
</div>

Lab1/5TF048_lab1/Views/Food/Finish.cshtml
@model _5TF048_lab1.Models.Dinner

@{
    ViewData["Title"] = "Finish";
}

<h1>hej hej</h1>

<div>
    <h4>Dinner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberofPortions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberofPortions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Review)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Review)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Egg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Egg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Milk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Milk)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Start">Back to List</a>
</div>

Lab1/5TF048_lab1/Views/Food/Recept.cshtml
@model _5TF048_lab1.Models.Dinner

@{
    ViewData["Title"] = "Recept";
}

<h1>Recept @Html.DisplayFor(model => model.NumberofPortions) portioner.</h1>

<div>
    <h4>Dinner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flour)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Egg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Egg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Milk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Milk)
        </dd>

    </dl>
</div>
<div>
    <p>What did you think about the food?</p>
    <a asp-action="Evaluate">Evaluate</a>
</div>

<div>
    <a asp-action="Start">Back to Start</a>
</div>

Lab1/5TF048_lab1/Views/Food/Start.cshtml
@model _5TF048_lab1.Models.Dinner

@{
    ViewData["Title"] = "Start";
}

<h2>Its time to cook some food!</h2>

<p>Fill name, nr of porions and date</p>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Recept" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberofPortions" class="control-label"></label>
                <input asp-for="NumberofPortions" class="form-control" />
                <span asp-validation-for="NumberofPortions" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Get recept" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Lab1/5TF048_lab1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Hello from our View Template!</p>

Lab1/5TF048_lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _5TF048_lab1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_5TF048_lab1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_5TF048_lab1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="Start">Food Helper</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _5TF048_lab1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>